# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd Wallpapers
    java -version
    printf 'walls\nlakshit\nhttps://raw.githubusercontent.com/mehulagg/Images/master/Wallpapers/\nLakshit\nY' | java -jar cre8json.jar
- script: |
    git config --global user.email "jonygupta80@gmail.com"
    git config --global user.name "Jony gupta"
    git commit -m "update walls.json"
    git remote add origin https://jonygupta80@dev.azure.com/jonygupta80/Wallpapers/_git/Images
    git push -u origin --all
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
